# This is a basic workflow to help you get started with Actions

name: createTestHtml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install XMLLint
        run: sudo apt  install libxml2-utils
      - name: Test loop
        run: |
          for file in ./templates/*; do
            name=$(xmllint --xpath "/kata/name/text()" $file)
            description=$(xmllint --xpath "/kata/description/text()" $file)
            text=$(xmllint --xpath "/kata/text" $file)
            htmlfile="${name,,}.html"
            echo $htmlfile

            echo "" > $htmlfile
            echo "<!DOCTYPE html>" >> $htmlfile
            echo "<html lang=\"en\">" >> $htmlfile
            echo "  <head>" >> $htmlfile
            echo "    <title>$name</title>" >> $htmlfile
            echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> $htmlfile
            echo "    <meta name=\"description\" content=\"$description\">" >> $htmlfile
            echo "    <meta charset=\"UTF-8\">" >> $htmlfile
            echo "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">" >> $htmlfile
            echo "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>" >> $htmlfile
            echo "    <link href=\"https://fonts.googleapis.com/css2?family=Kaisei+Tokumin&display=swap\" rel=\"stylesheet\">" >> $htmlfile
            echo "    <link href=\"style.css\" type=\"text/css\" rel=\"stylesheet\">" >> $htmlfile
            echo "    <link rel=\"shortcut icon\" href=\"favicon.ico\" type=\"image/x-icon\">" >> $htmlfile
            echo "  </head>" >> $htmlfile
            echo "  <body>" >> $htmlfile
            echo "    <h1><a href=\"index.html\">Kata > $name</h1>" >> $htmlfile
            echo "    $text" >> $htmlfile
            echo "  </body>" >> $htmlfile
            echo "</html>" >> $htmlfile
          done
      - name: Add all changes
        run: git add --all
      - name: Status
        run: git status
      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
